/**
 * Prospect intelligence model.
 *
 * Milestone 3D introduces persistent prospect intelligence.
 *
 * A prospect is NOT simply a real organization or person discovered on the
 * web. A prospect is an entity for which the system has:
 *
 * 1. verified identity;
 * 2. source-backed evidence;
 * 3. a meaningful product-relevance reason; and
 * 4. a meaningful observable opportunity / need signal.
 *
 * This model deliberately does NOT represent a CRM or outreach system.
 *
 * Prospect records must not be interpreted as confirmed customers,
 * qualified buyers, or expressions of buying intent unless the evidence
 * explicitly supports those conclusions.
 *
 * Milestone 3D.9:
 *
 * - email is now a first-class prospect contact field;
 * - email remains optional at this model layer while the prospecting
 *   executor is upgraded to discover and supply legitimate usable emails;
 * - defensive JSON parsing;
 * - defensive field normalization;
 * - explicit ownership enforcement;
 * - safe filtering;
 * - protection against malformed persisted evidence;
 * - preservation of optional fields as undefined rather than fabricated data;
 * - minimum prospect-quality requirements at the persistence boundary;
 * - validation of evidence sources as HTTP(S) URLs.
 */

import { randomUUID } from "crypto";
import { getDb } from "../db";
import type { InArgs } from "@/lib/db";

export type ProspectType =
  | "person"
  | "organization"
  | "partner"
  | "investor"
  | "customer"
  | "publisher"
  | "other";

export type ProspectQualificationStatus =
  | "candidate"
  | "qualified"
  | "unqualified"
  | "needs_review";

export interface ProspectEvidence {
  observation: string;
  source: string;
  observed_at?: string;
}

export interface Prospect {
  id: string;

  user_id: string;
  source_task_id?: string;

  name: string;
  organization?: string;
  role?: string;

  /**
   * A legitimate, usable contact email discovered through research.
   *
   * This is deliberately a first-class field rather than being buried inside
   * evidence. It remains optional here because the prospecting executor is
   * responsible for establishing whether an email can be found.
   */
  email?: string;

  prospect_type: ProspectType;
  qualification_status: ProspectQualificationStatus;

  website?: string;
  public_profile_url?: string;
  /** The prospect's own country, when known — see src/lib/timezones.ts for how this drives send timing. */
  country?: string;

  product_id?: string;
  fit_reason?: string;
  opportunity_signal?: string;

  evidence: ProspectEvidence[];
  confidence?: number;
  unknowns: string[];

  /**
   * MILESTONE 3F — Follow-up campaigns.
   *
   * sequence_status starts "not_started" and moves forward as outreach
   * progresses. "pending_approval" only happens when Settings'
   * require_manual_approval is on; otherwise a sequence goes straight to
   * "active" once its first email sends.
   */
  sequence_status:
    | "not_started"
    | "pending_approval"
    | "active"
    | "completed"
    | "unsubscribed"
    | "responded"
    | "paused"
    | "in_conversation"
    | "needs_human_reply"
    | "bounced";
  emails_sent: number;
  last_sent_at?: string;
  next_send_at?: string;
  /**
   * Used to build this prospect's one-click unsubscribe link. Generated
   * once, the first time a sequence starts — never guessable, never
   * derived from anything public about the prospect.
   */
  unsubscribe_token?: string;

  /**
   * MILESTONE 4R — set when the AI checking "does this disqualified
   * prospect fit another product" is genuinely uncertain between
   * candidates, rather than confident enough to auto-reassign or
   * auto-delete. candidate_product_names holds its suggested options
   * for a person to choose from.
   */
  needs_product_decision?: boolean;
  candidate_product_names?: string[];

  created_at: string;
  updated_at: string;
}

/**
 * Input required to create a prospect.
 *
 * id and timestamps are generated by the persistence layer.
 */
export interface CreateProspectInput {
  user_id: string;
  source_task_id?: string;

  name: string;
  organization?: string;
  role?: string;

  /**
   * Optional contact email.
   *
   * The prospecting executor will be responsible for ensuring that a
   * persisted task-generated prospect has a legitimate usable email.
   */
  email?: string;

  prospect_type: ProspectType;
  qualification_status?: ProspectQualificationStatus;

  website?: string;
  public_profile_url?: string;
  country?: string;

  product_id?: string;
  fit_reason?: string;
  opportunity_signal?: string;

  evidence?: ProspectEvidence[];
  confidence?: number;
  unknowns?: string[];
}

/* -------------------------------------------------------------------------- */
/* Constants                                                                  */
/* -------------------------------------------------------------------------- */

const VALID_PROSPECT_TYPES: ProspectType[] = [
  "person",
  "organization",
  "partner",
  "investor",
  "customer",
  "publisher",
  "other",
];

const VALID_QUALIFICATION_STATUSES: ProspectQualificationStatus[] = [
  "candidate",
  "qualified",
  "unqualified",
  "needs_review",
];

const MAX_NAME_LENGTH = 500;
const MAX_TEXT_LENGTH = 10_000;
const MAX_EMAIL_LENGTH = 320;
const MAX_EVIDENCE_ITEMS = 100;
const MAX_UNKNOWN_ITEMS = 100;

/* -------------------------------------------------------------------------- */
/* Utility functions                                                          */
/* -------------------------------------------------------------------------- */

function optionalString(
  value: unknown,
  maxLength = MAX_TEXT_LENGTH
): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }

  const trimmed = value.trim();

  if (!trimmed) {
    return undefined;
  }

  return trimmed.slice(0, maxLength);
}

function normalizeEmail(
  value: unknown
): string | undefined {
  const email = optionalString(
    value,
    MAX_EMAIL_LENGTH
  );

  if (!email) {
    return undefined;
  }

  /*
   * This is intentionally a conservative syntax check rather than an
   * attempt to verify mailbox existence.
   *
   * The prospecting executor is responsible for establishing the provenance
   * and legitimacy of the discovered address through public evidence.
   */
  const emailPattern =
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  if (!emailPattern.test(email)) {
    return undefined;
  }

  return email.toLowerCase();
}

function requiredString(
  value: unknown,
  fieldName: string,
  maxLength = MAX_TEXT_LENGTH
): string {
  if (typeof value !== "string") {
    throw new Error(`${fieldName} is required.`);
  }

  const trimmed = value.trim();

  if (!trimmed) {
    throw new Error(`${fieldName} is required.`);
  }

  return trimmed.slice(0, maxLength);
}

function isProspectType(value: unknown): value is ProspectType {
  return (
    typeof value === "string" &&
    VALID_PROSPECT_TYPES.includes(value as ProspectType)
  );
}

function isQualificationStatus(
  value: unknown
): value is ProspectQualificationStatus {
  return (
    typeof value === "string" &&
    VALID_QUALIFICATION_STATUSES.includes(
      value as ProspectQualificationStatus
    )
  );
}

/**
 * Returns true only for an actual HTTP(S) URL.
 *
 * Evidence sources are persisted intelligence and therefore must not be
 * allowed to contain arbitrary text masquerading as a source.
 */
function isValidHttpUrl(value: string): boolean {
  try {
    const url = new URL(value.trim());

    return (
      url.protocol === "http:" ||
      url.protocol === "https:"
    );
  } catch {
    return false;
  }
}

function parseJsonObject<T>(
  value: unknown,
  fallback: T
): T {
  if (typeof value !== "string" || !value.trim()) {
    return fallback;
  }

  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

function normalizeEvidence(value: unknown): ProspectEvidence[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .slice(0, MAX_EVIDENCE_ITEMS)
    .map((item): ProspectEvidence | null => {
      if (!item || typeof item !== "object") {
        return null;
      }

      const record = item as Record<string, unknown>;

      const observation = optionalString(
        record.observation,
        MAX_TEXT_LENGTH
      );

      const source = optionalString(
        record.source,
        MAX_TEXT_LENGTH
      );

      /*
       * Evidence is persisted intelligence.
       *
       * A source must therefore be a genuine HTTP(S) URL rather than
       * arbitrary text supplied by a caller or malformed persisted data.
       */
      if (
        !observation ||
        !source ||
        !isValidHttpUrl(source)
      ) {
        return null;
      }

      const observedAt = optionalString(
        record.observed_at,
        100
      );

      return {
        observation,
        source,
        ...(observedAt
          ? { observed_at: observedAt }
          : {}),
      };
    })
    .filter(
      (item): item is ProspectEvidence =>
        item !== null
    );
}

function normalizeUnknowns(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .slice(0, MAX_UNKNOWN_ITEMS)
    .filter(
      (item): item is string =>
        typeof item === "string" &&
        item.trim().length > 0
    )
    .map((item) =>
      item.trim().slice(0, MAX_TEXT_LENGTH)
    );
}

/**
 * Converts a database row into the public Prospect model.
 *
 * Database contents are treated as untrusted persisted data. Malformed JSON
 * must not crash the application merely because a single prospect contains
 * damaged evidence or unknowns.
 */
function mapProspectRow(
  row: Record<string, unknown>
): Prospect {
  const prospectType = isProspectType(row.prospect_type)
    ? row.prospect_type
    : "other";

  const qualificationStatus =
    isQualificationStatus(row.qualification_status)
      ? row.qualification_status
      : "needs_review";

  const evidence = normalizeEvidence(
    parseJsonObject<unknown[]>(
      row.evidence,
      []
    )
  );

  const unknowns = normalizeUnknowns(
    parseJsonObject<unknown[]>(
      row.unknowns,
      []
    )
  );

  const confidence =
    row.confidence === null ||
    row.confidence === undefined
      ? undefined
      : Number(row.confidence);

  return {
    id: String(row.id),

    user_id: String(row.user_id),

    source_task_id:
      row.source_task_id === null ||
      row.source_task_id === undefined
        ? undefined
        : optionalString(row.source_task_id),

    name:
      optionalString(row.name, MAX_NAME_LENGTH) ??
      "Unnamed prospect",

    organization:
      optionalString(
        row.organization,
        MAX_NAME_LENGTH
      ),

    role:
      optionalString(
        row.role,
        MAX_NAME_LENGTH
      ),

    email:
      normalizeEmail(row.email),

    prospect_type: prospectType,

    qualification_status:
      qualificationStatus,

    website:
      optionalString(
        row.website,
        MAX_TEXT_LENGTH
      ),

    country:
      optionalString(
        row.country,
        200
      ),

    public_profile_url:
      optionalString(
        row.public_profile_url,
        MAX_TEXT_LENGTH
      ),

    product_id:
      optionalString(row.product_id, 200),

    fit_reason:
      optionalString(row.fit_reason),

    opportunity_signal:
      optionalString(row.opportunity_signal),

    evidence,

    confidence:
      Number.isFinite(confidence)
        ? Math.min(
            Math.max(confidence as number, 0),
            1
          )
        : undefined,

    unknowns,

    sequence_status:
      typeof row.sequence_status === "string"
        ? (row.sequence_status as Prospect["sequence_status"])
        : "not_started",

    emails_sent:
      row.emails_sent === null ||
      row.emails_sent === undefined
        ? 0
        : Number(row.emails_sent),

    last_sent_at:
      optionalString(row.last_sent_at),

    next_send_at:
      optionalString(row.next_send_at),

    unsubscribe_token:
      optionalString(row.unsubscribe_token, 200),

    needs_product_decision:
      row.needs_product_decision === true || row.needs_product_decision === "true",

    candidate_product_names:
      parseJsonObject<string[]>(row.candidate_product_names, []),

    created_at:
      String(row.created_at),

    updated_at:
      String(row.updated_at),
  };
}

/* -------------------------------------------------------------------------- */
/* Create                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Creates and persists a prospect intelligence record.
 *
 * Persistence quality rules:
 *
 * - a prospect must have at least one valid evidence item;
 * - a prospect must explain why it fits the target product;
 * - a prospect must contain an observable opportunity / need signal;
 * - a product-linked prospect must identify the product;
 * - evidence is normalized before persistence;
 * - every evidence source must be a valid HTTP(S) URL;
 * - an email, when supplied, must have valid basic email syntax.
 *
 * Email is intentionally not yet a mandatory persistence requirement.
 * The prospecting executor will be upgraded separately to make email-first
 * prospect discovery the operational rule for task-generated prospects.
 */
export async function createProspect(
  input: CreateProspectInput
): Promise<Prospect> {
  const userId = requiredString(
    input.user_id,
    "Prospect user_id",
    500
  );

  const name = requiredString(
    input.name,
    "Prospect name",
    MAX_NAME_LENGTH
  );

  if (!isProspectType(input.prospect_type)) {
    throw new Error(
      `Invalid prospect_type "${input.prospect_type}".`
    );
  }

  const qualificationStatus =
    input.qualification_status ??
    "candidate";

  if (!isQualificationStatus(qualificationStatus)) {
    throw new Error(
      `Invalid qualification_status "${qualificationStatus}".`
    );
  }

  if (
    input.confidence !== undefined &&
    (
      !Number.isFinite(input.confidence) ||
      input.confidence < 0 ||
      input.confidence > 1
    )
  ) {
    throw new Error(
      "Prospect confidence must be between 0 and 1."
    );
  }

  const evidence = normalizeEvidence(
    input.evidence ?? []
  );

  if (evidence.length === 0) {
    throw new Error(
      "A prospect must contain at least one valid HTTP(S) evidence item."
    );
  }

  const fitReason = optionalString(
    input.fit_reason
  );

  if (!fitReason) {
    throw new Error(
      "A prospect must contain a meaningful fit_reason."
    );
  }

  const opportunitySignal = optionalString(
    input.opportunity_signal
  );

  if (!opportunitySignal) {
    throw new Error(
      "A prospect must contain a meaningful opportunity_signal."
    );
  }

  const productId =
    optionalString(input.product_id, 200);

  /*
   * Prospecting intelligence should always be associated with the product
   * that the research was performed for.
   *
   * This does not prevent future non-product prospect records, but it does
   * prevent a product-specific prospecting task from silently persisting
   * productless records.
   */
  if (input.source_task_id && !productId) {
    throw new Error(
      "A task-generated prospect must identify its target product."
    );
  }

const email =
  normalizeEmail(input.email);

/*
 * Email is now the contactability gate for task-generated prospects.
 *
 * Existing prospect records remain compatible with nullable email, but a
 * new prospect created from a task must have a syntactically valid email.
 *
 * This does NOT claim that the mailbox exists. The prospecting executor must
 * establish that the address was legitimately discovered from a public
 * source and preserve that provenance in the evidence.
 */
if (input.source_task_id && !email) {
  throw new Error(
    "A task-generated prospect must contain a valid email address."
  );
}

/*
 * For non-task-created prospects, an email is optional. If one is supplied,
 * however, it must still have valid basic syntax.
 */
if (
  !input.source_task_id &&
  input.email !== undefined &&
  input.email !== null &&
  input.email !== "" &&
  !email
) {
  throw new Error(
    "Prospect email must be a valid email address."
  );
}

  const unknowns = normalizeUnknowns(
    input.unknowns ?? []
  );

  const db = await getDb();

  const id = randomUUID();

  await db.execute({
    sql: `
      INSERT INTO prospects (
        id,
        user_id,
        source_task_id,
        name,
        organization,
        role,
        email,
        prospect_type,
        qualification_status,
        website,
        public_profile_url,
        country,
        product_id,
        fit_reason,
        opportunity_signal,
        evidence,
        confidence,
        unknowns
      )
      VALUES (
        @id,
        @user_id,
        @source_task_id,
        @name,
        @organization,
        @role,
        @email,
        @prospect_type,
        @qualification_status,
        @website,
        @public_profile_url,
        @country,
        @product_id,
        @fit_reason,
        @opportunity_signal,
        @evidence,
        @confidence,
        @unknowns
      )
    `,
    args: {
      id,

      user_id: userId,

      source_task_id:
        optionalString(
          input.source_task_id,
          200
        ) ?? null,

      name,

      organization:
        optionalString(
          input.organization,
          MAX_NAME_LENGTH
        ) ?? null,

      role:
        optionalString(
          input.role,
          MAX_NAME_LENGTH
        ) ?? null,

      email:
        email ?? null,

      prospect_type:
        input.prospect_type,

      qualification_status:
        qualificationStatus,

      website:
        optionalString(
          input.website,
          MAX_TEXT_LENGTH
        ) ?? null,

      public_profile_url:
        optionalString(
          input.public_profile_url,
          MAX_TEXT_LENGTH
        ) ?? null,

      country:
        optionalString(
          input.country,
          200
        ) ?? null,

      product_id:
        productId ?? null,

      fit_reason:
        fitReason,

      opportunity_signal:
        opportunitySignal,

      evidence:
        JSON.stringify(evidence),

      confidence:
        input.confidence ?? null,

      unknowns:
        JSON.stringify(unknowns),
    },
  });

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE id = ?
        AND user_id = ?
    `,
    args: [id, userId],
  });

  const row = result.rows[0] as unknown as
    | Record<string, unknown>
    | undefined;

  if (!row) {
    throw new Error(
      "Failed to retrieve newly created prospect."
    );
  }

  return mapProspectRow(row);
}

/* -------------------------------------------------------------------------- */
/* Retrieval                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Retrieves a prospect by ID belonging to the specified user.
 *
 * Ownership is part of the query itself so a prospect belonging to another
 * user can never be returned accidentally.
 */
export async function getProspectById(
  userId: string,
  id: string
): Promise<Prospect | null> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();

  if (
    !normalizedUserId ||
    !normalizedId
  ) {
    return null;
  }

  const db = await getDb();

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE id = ?
        AND user_id = ?
      LIMIT 1
    `,
    args: [normalizedId, normalizedUserId],
  });

  const row = result.rows[0] as unknown as
    | Record<string, unknown>
    | undefined;

  return row
    ? mapProspectRow(row)
    : null;
}

/**
 * Lists prospects belonging to a specific user, newest first.
 *
 * All filters are parameterized. The LIMIT value is normalized to prevent
 * invalid or unexpectedly large queries.
 */
export async function listProspects(
  userId: string,
  options?: {
    limit?: number;
    qualification_status?: ProspectQualificationStatus;
    prospect_type?: ProspectType;
    product_id?: string;
  }
): Promise<Prospect[]> {
  const normalizedUserId =
    userId.trim();

  if (!normalizedUserId) {
    return [];
  }

  const db = await getDb();

  const requestedLimit =
    typeof options?.limit === "number" &&
    Number.isFinite(options.limit)
      ? Math.floor(options.limit)
      : 50;

  const limit = Math.min(
    Math.max(requestedLimit, 1),
    200
  );

  const conditions: string[] = [
    "user_id = @user_id",
  ];

  const parameters: Record<
    string,
    unknown
  > = {
    user_id: normalizedUserId,
    limit,
  };

  if (options?.qualification_status) {
    if (
      !isQualificationStatus(
        options.qualification_status
      )
    ) {
      return [];
    }

    conditions.push(
      "qualification_status = @qualification_status"
    );

    parameters.qualification_status =
      options.qualification_status;
  }

  if (options?.prospect_type) {
    if (
      !isProspectType(
        options.prospect_type
      )
    ) {
      return [];
    }

    conditions.push(
      "prospect_type = @prospect_type"
    );

    parameters.prospect_type =
      options.prospect_type;
  }

  if (options?.product_id) {
    const productId =
      options.product_id.trim();

    if (!productId) {
      return [];
    }

    conditions.push(
      "product_id = @product_id"
    );

    parameters.product_id =
      productId;
  }

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE ${conditions.join(" AND ")}
      ORDER BY created_at DESC
      LIMIT @limit
    `,
    args: parameters as InArgs,
  });

  const rows = result.rows as unknown as Array<
    Record<string, unknown>
  >;

  return rows.map(mapProspectRow);
}

/**
 * Updates a prospect's qualification status.
 *
 * This is intentionally narrow — the Prospects view lets a person triage
 * (qualified / not a fit / needs review) what the research already
 * gathered. It does not let evidence, contact details, or other
 * research-derived fields be edited here; those come only from the
 * prospecting executor's own evidence-backed process.
 */
export async function updateProspect(
  userId: string,
  id: string,
  fields: { qualification_status: ProspectQualificationStatus }
): Promise<Prospect> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();

  if (!normalizedUserId || !normalizedId) {
    throw new Error("A user and prospect id are required.");
  }

  if (!isQualificationStatus(fields.qualification_status)) {
    throw new Error(
      `"${fields.qualification_status}" is not a valid qualification status.`
    );
  }

  const db = await getDb();

  const result = await db.execute({
    sql: `
      UPDATE prospects
      SET
        qualification_status = @qualification_status,
        updated_at = @updated_at
      WHERE id = @id
        AND user_id = @user_id
    `,
    args: {
      id: normalizedId,
      user_id: normalizedUserId,
      qualification_status: fields.qualification_status,
      updated_at: new Date().toISOString(),
    },
  });

  if (result.rowsAffected === 0) {
    throw new Error("Prospect not found.");
  }

  const updated = await getProspectById(normalizedUserId, normalizedId);

  if (!updated) {
    throw new Error("Prospect was updated but could not be retrieved afterward.");
  }

  return updated;
}

/**
 * MILESTONE 3S — genuine deep qualification.
 *
 * Applies the result of an actual research-driven qualification pass —
 * not the old one-line "confidence >= threshold" check against a number
 * assigned once during discovery, but a real decision made after fresh,
 * targeted research specifically about whether THIS prospect should be
 * qualified. Updates confidence and fit_reason to reflect that fresh
 * research, and appends any new evidence found along the way rather than
 * discarding it.
 */
export async function applyDeepQualificationResult(
  userId: string,
  prospectId: string,
  result: {
    qualification_status: "qualified" | "unqualified";
    confidence: number;
    fit_reason: string;
    additional_evidence: ProspectEvidence[];
  }
): Promise<Prospect> {
  const normalizedUserId = userId.trim();
  const normalizedId = prospectId.trim();

  if (!normalizedUserId || !normalizedId) {
    throw new Error("A user and prospect id are required.");
  }

  const existing = await getProspectById(normalizedUserId, normalizedId);
  if (!existing) {
    throw new Error("Prospect not found.");
  }

  const mergedEvidence = [
    ...existing.evidence,
    ...result.additional_evidence,
  ];

  const db = await getDb();

  await db.execute({
    sql: `
      UPDATE prospects
      SET
        qualification_status = @qualification_status,
        confidence = @confidence,
        fit_reason = @fit_reason,
        evidence = @evidence,
        updated_at = @updated_at
      WHERE id = @id
        AND user_id = @user_id
    `,
    args: {
      id: normalizedId,
      user_id: normalizedUserId,
      qualification_status: result.qualification_status,
      confidence: result.confidence,
      fit_reason: result.fit_reason,
      evidence: JSON.stringify(mergedEvidence),
      updated_at: new Date().toISOString(),
    },
  });

  const updated2 = await getProspectById(normalizedUserId, normalizedId);
  if (!updated2) {
    throw new Error("Prospect was updated but could not be retrieved afterward.");
  }
  return updated2;
}

/* -------------------------------------------------------------------------- */
/* MILESTONE 3F — Follow-up campaigns                                        */
/* -------------------------------------------------------------------------- */

/**
 * Prospects eligible to receive the next email in their sequence right now:
 * either they haven't started one yet (and are qualified), or they're
 * active and their next scheduled send is due.
 *
 * includePendingApproval: when Settings' require_manual_approval is
 * currently OFF, a prospect stuck in "pending_approval" from an earlier
 * run (back when approval WAS required) should become eligible again on
 * its own — the gate that put them there no longer applies. Without this,
 * turning approval off would silently do nothing for anyone already
 * caught by it; they'd stay stuck until manually approved one at a time.
 * The caller (executors/emailCampaign.ts) decides this based on the
 * current setting value.
 *
 * Still never includes unsubscribed, responded, paused, or completed —
 * those are genuinely terminal or waiting on a person's action, not on
 * settings or time.
 */
export async function listProspectsDueForOutreach(
  userId: string,
  limit: number,
  includePendingApproval = false
): Promise<Prospect[]> {
  const normalizedUserId = userId.trim();
  if (!normalizedUserId) return [];

  const db = await getDb();
  const nowIso = new Date().toISOString();

  const result = await db.execute({
    sql: `
      SELECT prospects.*
      FROM prospects
      LEFT JOIN products ON products.id = prospects.product_id
      WHERE prospects.user_id = @user_id
        AND prospects.qualification_status = 'qualified'
        AND prospects.email IS NOT NULL
        AND (products.campaign_paused IS NULL OR products.campaign_paused = false)
        AND (products.approval_status IS NULL OR products.approval_status = 'approved')
        AND (
          prospects.sequence_status = 'not_started'
          OR (prospects.sequence_status = 'active' AND prospects.next_send_at IS NOT NULL AND prospects.next_send_at <= @now)
          OR (@include_pending_approval AND prospects.sequence_status = 'pending_approval')
        )
      ORDER BY
        CASE WHEN prospects.sequence_status = 'active' THEN 0 ELSE 1 END,
        prospects.next_send_at ASC NULLS FIRST,
        prospects.created_at ASC
      LIMIT @limit
    `,
    args: {
      user_id: normalizedUserId,
      now: nowIso,
      limit: Math.min(Math.max(Math.floor(limit), 1), 200),
      include_pending_approval: includePendingApproval,
    },
  });

  return (result.rows as unknown as Array<Record<string, unknown>>).map(
    mapProspectRow
  );
}

/**
 * Narrow update for the sequence-tracking fields only. Deliberately
 * separate from updateProspect() (qualification triage) and createProspect
 * (research-derived fields) — this is the one place sending state changes.
 */
export async function updateProspectSequence(
  userId: string,
  id: string,
  fields: {
    sequence_status?: Prospect["sequence_status"];
    emails_sent?: number;
    last_sent_at?: string | null;
    next_send_at?: string | null;
    unsubscribe_token?: string;
  }
): Promise<Prospect> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();

  if (!normalizedUserId || !normalizedId) {
    throw new Error("A user and prospect id are required.");
  }

  const entries = Object.entries(fields).filter(
    ([, v]) => v !== undefined
  );

  if (entries.length === 0) {
    const current = await getProspectById(normalizedUserId, normalizedId);
    if (!current) throw new Error("Prospect not found.");
    return current;
  }

  const db = await getDb();

  const setClause = entries
    .map(([key]) => `${key} = @${key}`)
    .join(", ");

  const args: Record<string, unknown> = {
    id: normalizedId,
    user_id: normalizedUserId,
    updated_at: new Date().toISOString(),
  };

  for (const [key, value] of entries) {
    args[key] = value;
  }

  const result = await db.execute({
    sql: `
      UPDATE prospects
      SET ${setClause}, updated_at = @updated_at
      WHERE id = @id AND user_id = @user_id
    `,
    args,
  });

  if (result.rowsAffected === 0) {
    throw new Error("Prospect not found.");
  }

  const updated = await getProspectById(normalizedUserId, normalizedId);
  if (!updated) {
    throw new Error("Prospect was updated but could not be retrieved afterward.");
  }

  return updated;
}

/**
 * Public lookup by unsubscribe token — deliberately NOT scoped to a
 * user_id, since the person clicking an unsubscribe link in their inbox
 * isn't authenticated into this app at all. The token itself (random,
 * generated once, never derived from anything guessable) is what proves
 * this is the right prospect.
 */
export async function getProspectByUnsubscribeToken(
  token: string
): Promise<Prospect | null> {
  const normalizedToken = token.trim();
  if (!normalizedToken) return null;

  const db = await getDb();

  const result = await db.execute({
    sql: `SELECT * FROM prospects WHERE unsubscribe_token = ? LIMIT 1`,
    args: [normalizedToken],
  });

  const row = result.rows[0] as unknown as
    | Record<string, unknown>
    | undefined;

  return row ? mapProspectRow(row) : null;
}

/**
 * Every currently-active or pending-approval sequence, for the Follow-ups
 * view.
 */
export async function listActiveSequences(
  userId: string
): Promise<Prospect[]> {
  const normalizedUserId = userId.trim();
  if (!normalizedUserId) return [];

  const db = await getDb();

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE user_id = @user_id
        AND sequence_status IN ('pending_approval', 'active', 'completed', 'responded', 'unsubscribed', 'paused', 'in_conversation', 'needs_human_reply', 'bounced')
      ORDER BY
        CASE sequence_status
          WHEN 'needs_human_reply' THEN 0
          WHEN 'pending_approval' THEN 1
          WHEN 'in_conversation' THEN 2
          WHEN 'active' THEN 3
          WHEN 'paused' THEN 4
          WHEN 'responded' THEN 5
          WHEN 'completed' THEN 6
          WHEN 'bounced' THEN 7
          WHEN 'unsubscribed' THEN 8
          ELSE 9
        END,
        updated_at DESC
      LIMIT 200
    `,
    args: { user_id: normalizedUserId },
  });

  return (result.rows as unknown as Array<Record<string, unknown>>).map(
    mapProspectRow
  );
}
/**
 * MILESTONE 3I — Full autonomy, opted into explicitly.
 *
 * Promotes "needs_review" prospects to "qualified" — with no human
 * involved at all — once their confidence score clears the given
 * threshold. This is a genuine increase in autonomy (and risk) over the
 * baseline: the prospecting agent already auto-qualifies prospects it's
 * confident about; this removes the human safety net for the ones it
 * was NOT confident about, for anyone who has explicitly turned on
 * Settings' autonomous_qualification.
 *
 * Deliberately narrow: only ever touches "needs_review" rows. Never
 * touches "unqualified" (the AI actively rejected these for a reason)
 * or "candidate" (a distinctly more tentative bucket than needs_review).
 *
 * Returns the number of prospects promoted, for logging/activity.
 */
export async function autoQualifyDueProspects(
  userId: string,
  confidenceThreshold: number
): Promise<number> {
  const normalizedUserId = userId.trim();
  if (!normalizedUserId) return 0;

  const db = await getDb();

  const result = await db.execute({
    sql: `
      UPDATE prospects
      SET qualification_status = 'qualified', updated_at = @updated_at
      WHERE user_id = @user_id
        AND qualification_status = 'needs_review'
        AND confidence IS NOT NULL
        AND confidence >= @threshold
    `,
    args: {
      user_id: normalizedUserId,
      threshold: confidenceThreshold,
      updated_at: new Date().toISOString(),
    },
  });

  return result.rowsAffected;
}

/**
 * MILESTONE 3J — Inbound email.
 *
 * Finds a prospect by their email address (case-insensitive) — used to
 * match an inbound reply's sender back to the prospect record it belongs
 * to. Excludes unsubscribed prospects: if someone unsubscribed and then
 * emails in anyway, that's still worth seeing in the inbound log, but
 * should not be matched back into an active conversation.
 */
export async function getProspectByEmail(
  userId: string,
  email: string
): Promise<Prospect | null> {
  const normalizedUserId = userId.trim();
  const normalizedEmail = email.trim().toLowerCase();

  if (!normalizedUserId || !normalizedEmail) return null;

  const db = await getDb();

  const result = await db.execute({
    sql: `
      SELECT * FROM prospects
      WHERE user_id = ?
        AND lower(email) = ?
      LIMIT 1
    `,
    args: [normalizedUserId, normalizedEmail],
  });

  const row = result.rows[0] as unknown as Record<string, unknown> | undefined;
  return row ? mapProspectRow(row) : null;
}

/**
 * All distinct, non-null prospect emails for a user — used by bounce
 * detection to recognize which address in a bounce report is actually
 * one of ours.
 */
export async function listAllProspectEmails(
  userId: string
): Promise<Set<string>> {
  const normalizedUserId = userId.trim();
  if (!normalizedUserId) return new Set();

  const db = await getDb();

  const result = await db.execute({
    sql: `SELECT DISTINCT lower(email) as email FROM prospects WHERE user_id = ? AND email IS NOT NULL`,
    args: [normalizedUserId],
  });

  return new Set(
    (result.rows as unknown as Array<{ email: string }>).map((r) => r.email)
  );
}

/**
 * MILESTONE 3L — improvement #5: safer, wider reply matching.
 *
 * Finds a prospect whose stored email is on the given domain — used to
 * flag a "possible match" when someone replies from a different address
 * than the one on file (e.g. a personal Gmail instead of their work
 * email). Deliberately just a signal for a person to review, never used
 * to auto-link a reply to a conversation: matching the wrong person's
 * domain and having the AI reply as if continuing THEIR conversation
 * would be a real, meaningful mistake, worse than just missing the
 * message entirely.
 */
export async function findProspectByDomain(
  userId: string,
  domain: string
): Promise<Prospect | null> {
  const normalizedUserId = userId.trim();
  const normalizedDomain = domain.trim().toLowerCase();
  if (!normalizedUserId || !normalizedDomain) return null;

  const db = await getDb();

  const result = await db.execute({
    sql: `
      SELECT * FROM prospects
      WHERE user_id = ?
        AND lower(email) LIKE ?
      LIMIT 1
    `,
    args: [normalizedUserId, `%@${normalizedDomain}`],
  });

  const row = result.rows[0] as unknown as Record<string, unknown> | undefined;
  return row ? mapProspectRow(row) : null;
}

/**
 * MILESTONE 3N — export/import.
 *
 * listProspects() is deliberately capped at 200 for the Prospects page's
 * sake — a real export needs everything, not a UI-sized page of it. Kept
 * as its own function rather than adding an "unlimited" escape hatch to
 * listProspects(), so that cap can never accidentally be bypassed from
 * somewhere it shouldn't be.
 */
export async function listAllProspectsForExport(
  userId: string
): Promise<Prospect[]> {
  const normalizedUserId = userId.trim();
  if (!normalizedUserId) return [];

  const db = await getDb();

  const result = await db.execute({
    sql: `SELECT * FROM prospects WHERE user_id = ? ORDER BY created_at ASC LIMIT 50000`,
    args: [normalizedUserId],
  });

  return (result.rows as unknown as Array<Record<string, unknown>>).map(
    mapProspectRow
  );
}

/**
 * MILESTONE 4E — deletion, from either the chat agent (explicit
 * instruction) or the auto-cleanup flow when disqualifying a prospect
 * with no fit for any other product.
 *
 * MILESTONE 4F — a real bug this fixes: email_sends and inbound_emails
 * both reference prospects via a foreign key with no ON DELETE CASCADE,
 * so any prospect with sent emails or inbound replies on record could
 * not actually be deleted — the database correctly refused with a
 * constraint violation, surfaced to Innocent as a confusing error for
 * a prospect he'd already been emailing. Deleting the related records
 * first, explicitly, is what "delete this prospect" should actually
 * mean — not "delete unless they have any history."
 */
export async function deleteProspect(userId: string, id: string): Promise<void> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();
  if (!normalizedUserId || !normalizedId) {
    throw new Error("A user and prospect id are required.");
  }

  const db = await getDb();

  await db.execute({
    sql: `DELETE FROM email_sends WHERE prospect_id = ? AND user_id = ?`,
    args: [normalizedId, normalizedUserId],
  });
  await db.execute({
    sql: `DELETE FROM inbound_emails WHERE prospect_id = ? AND user_id = ?`,
    args: [normalizedId, normalizedUserId],
  });

  const result = await db.execute({
    sql: `DELETE FROM prospects WHERE id = ? AND user_id = ?`,
    args: [normalizedId, normalizedUserId],
  });

  if (result.rowsAffected === 0) {
    throw new Error("Prospect not found.");
  }
}

/**
 * MILESTONE 4E — moves a prospect to a different product when they
 * don't fit the one they were originally found for, but genuinely do
 * fit another. Resets qualification to needs_review since they haven't
 * actually been evaluated against the NEW product yet — carrying over
 * "qualified" or "unqualified" from the old product would be
 * misleading. fit_reason is cleared for the same reason.
 */
export async function reassignProspectToProduct(
  userId: string,
  id: string,
  newProductId: string
): Promise<Prospect> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();
  if (!normalizedUserId || !normalizedId || !newProductId.trim()) {
    throw new Error("A user, prospect id, and new product id are required.");
  }

  const db = await getDb();
  const result = await db.execute({
    sql: `
      UPDATE prospects
      SET product_id = @product_id, qualification_status = 'needs_review', fit_reason = NULL, updated_at = @updated_at
      WHERE id = @id AND user_id = @user_id
    `,
    args: {
      product_id: newProductId,
      updated_at: new Date().toISOString(),
      id: normalizedId,
      user_id: normalizedUserId,
    },
  });

  if (result.rowsAffected === 0) {
    throw new Error("Prospect not found.");
  }

  const check = await db.execute({
    sql: `SELECT * FROM prospects WHERE id = ? AND user_id = ?`,
    args: [normalizedId, normalizedUserId],
  });
  const row = check.rows[0] as unknown as Record<string, unknown> | undefined;
  if (!row) {
    throw new Error("Prospect was updated but could not be retrieved afterward.");
  }
  return mapProspectRow(row);
}

/**
 * MILESTONE 4E — finds prospects by loose name/organization/email
 * matching, for the chat agent's delete_prospects tool. Not exact-match
 * only, since Innocent will refer to prospects conversationally
 * ("the 7 Groketer Mail Drip prospects that don't fit") rather than by
 * database ID.
 */
export async function findProspectsByLooseMatch(
  userId: string,
  query: string
): Promise<Prospect[]> {
  const normalizedUserId = userId.trim();
  if (!normalizedUserId || !query.trim()) return [];

  const db = await getDb();
  const pattern = `%${query.trim()}%`;

  const result = await db.execute({
    sql: `
      SELECT * FROM prospects
      WHERE user_id = ?
        AND (name ILIKE ? OR organization ILIKE ? OR email ILIKE ?)
      ORDER BY created_at DESC
      LIMIT 100
    `,
    args: [normalizedUserId, pattern, pattern, pattern],
  });

  return (result.rows as unknown as Array<Record<string, unknown>>).map(mapProspectRow);
}

/**
 * MILESTONE 4R — marks a prospect as needing a manual product-reassignment
 * decision, storing the AI's candidate suggestions for the UI to present.
 */
export async function markProspectNeedsProductDecision(
  userId: string,
  id: string,
  candidateProductNames: string[]
): Promise<void> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();
  if (!normalizedUserId || !normalizedId) {
    throw new Error("A user and prospect id are required.");
  }

  const db = await getDb();
  const result = await db.execute({
    sql: `
      UPDATE prospects
      SET needs_product_decision = true,
          candidate_product_names = @candidate_product_names,
          updated_at = @updated_at
      WHERE id = @id AND user_id = @user_id
    `,
    args: {
      candidate_product_names: JSON.stringify(candidateProductNames.slice(0, MAX_EVIDENCE_ITEMS)),
      updated_at: new Date().toISOString(),
      id: normalizedId,
      user_id: normalizedUserId,
    },
  });

  if (result.rowsAffected === 0) {
    throw new Error("Prospect not found.");
  }
}

/**
 * MILESTONE 4R — resolves a pending product-reassignment decision:
 * either reassigns to the chosen product (clearing the decision flag) or
 * deletes the prospect outright, based on what Innocent picks in the UI.
 */
export async function resolveProductDecision(
  userId: string,
  id: string,
  decision: { action: "reassign"; productId: string } | { action: "delete" }
): Promise<void> {
  if (decision.action === "delete") {
    await deleteProspect(userId, id);
    return;
  }

  await reassignProspectToProduct(userId, id, decision.productId);

  const db = await getDb();
  await db.execute({
    sql: `
      UPDATE prospects
      SET needs_product_decision = false, candidate_product_names = NULL
      WHERE id = @id AND user_id = @user_id
    `,
    args: { id: id.trim(), user_id: userId.trim() },
  });
}
