/**
 * Prospect intelligence model.
 *
 * Milestone 3D introduces persistent prospect intelligence.
 *
 * A prospect is NOT simply a real organization or person discovered on the
 * web. A prospect is an entity for which the system has:
 *
 * 1. verified identity;
 * 2. source-backed evidence;
 * 3. a meaningful product-relevance reason; and
 * 4. a meaningful observable opportunity / need signal.
 *
 * This model deliberately does NOT represent a CRM or outreach system.
 *
 * Prospect records must not be interpreted as confirmed customers,
 * qualified buyers, or expressions of buying intent unless the evidence
 * explicitly supports those conclusions.
 *
 * Milestone 3D.9:
 *
 * - email is now a first-class prospect contact field;
 * - email remains optional at this model layer while the prospecting
 *   executor is upgraded to discover and supply legitimate usable emails;
 * - defensive JSON parsing;
 * - defensive field normalization;
 * - explicit ownership enforcement;
 * - safe filtering;
 * - protection against malformed persisted evidence;
 * - preservation of optional fields as undefined rather than fabricated data;
 * - minimum prospect-quality requirements at the persistence boundary;
 * - validation of evidence sources as HTTP(S) URLs.
 */

import { randomUUID } from "crypto";
import { getDb } from "../db";
import type { InArgs } from "@/lib/db";

export type ProspectType =
  | "person"
  | "organization"
  | "partner"
  | "investor"
  | "customer"
  | "publisher"
  | "other";

export type ProspectQualificationStatus =
  | "candidate"
  | "qualified"
  | "unqualified"
  | "needs_review";

export interface ProspectEvidence {
  observation: string;
  source: string;
  observed_at?: string;
}

export interface Prospect {
  id: string;

  user_id: string;
  source_task_id?: string;

  name: string;
  organization?: string;
  role?: string;

  /**
   * A legitimate, usable contact email discovered through research.
   *
   * This is deliberately a first-class field rather than being buried inside
   * evidence. It remains optional here because the prospecting executor is
   * responsible for establishing whether an email can be found.
   */
  email?: string;

  prospect_type: ProspectType;
  qualification_status: ProspectQualificationStatus;

  website?: string;
  public_profile_url?: string;

  product_id?: string;
  fit_reason?: string;
  opportunity_signal?: string;

  evidence: ProspectEvidence[];
  confidence?: number;
  unknowns: string[];

  created_at: string;
  updated_at: string;
}

/**
 * Input required to create a prospect.
 *
 * id and timestamps are generated by the persistence layer.
 */
export interface CreateProspectInput {
  user_id: string;
  source_task_id?: string;

  name: string;
  organization?: string;
  role?: string;

  /**
   * Optional contact email.
   *
   * The prospecting executor will be responsible for ensuring that a
   * persisted task-generated prospect has a legitimate usable email.
   */
  email?: string;

  prospect_type: ProspectType;
  qualification_status?: ProspectQualificationStatus;

  website?: string;
  public_profile_url?: string;

  product_id?: string;
  fit_reason?: string;
  opportunity_signal?: string;

  evidence?: ProspectEvidence[];
  confidence?: number;
  unknowns?: string[];
}

/* -------------------------------------------------------------------------- */
/* Constants                                                                  */
/* -------------------------------------------------------------------------- */

const VALID_PROSPECT_TYPES: ProspectType[] = [
  "person",
  "organization",
  "partner",
  "investor",
  "customer",
  "publisher",
  "other",
];

const VALID_QUALIFICATION_STATUSES: ProspectQualificationStatus[] = [
  "candidate",
  "qualified",
  "unqualified",
  "needs_review",
];

const MAX_NAME_LENGTH = 500;
const MAX_TEXT_LENGTH = 10_000;
const MAX_EMAIL_LENGTH = 320;
const MAX_EVIDENCE_ITEMS = 100;
const MAX_UNKNOWN_ITEMS = 100;

/* -------------------------------------------------------------------------- */
/* Utility functions                                                          */
/* -------------------------------------------------------------------------- */

function optionalString(
  value: unknown,
  maxLength = MAX_TEXT_LENGTH
): string | undefined {
  if (typeof value !== "string") {
    return undefined;
  }

  const trimmed = value.trim();

  if (!trimmed) {
    return undefined;
  }

  return trimmed.slice(0, maxLength);
}

function normalizeEmail(
  value: unknown
): string | undefined {
  const email = optionalString(
    value,
    MAX_EMAIL_LENGTH
  );

  if (!email) {
    return undefined;
  }

  /*
   * This is intentionally a conservative syntax check rather than an
   * attempt to verify mailbox existence.
   *
   * The prospecting executor is responsible for establishing the provenance
   * and legitimacy of the discovered address through public evidence.
   */
  const emailPattern =
    /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  if (!emailPattern.test(email)) {
    return undefined;
  }

  return email.toLowerCase();
}

function requiredString(
  value: unknown,
  fieldName: string,
  maxLength = MAX_TEXT_LENGTH
): string {
  if (typeof value !== "string") {
    throw new Error(`${fieldName} is required.`);
  }

  const trimmed = value.trim();

  if (!trimmed) {
    throw new Error(`${fieldName} is required.`);
  }

  return trimmed.slice(0, maxLength);
}

function isProspectType(value: unknown): value is ProspectType {
  return (
    typeof value === "string" &&
    VALID_PROSPECT_TYPES.includes(value as ProspectType)
  );
}

function isQualificationStatus(
  value: unknown
): value is ProspectQualificationStatus {
  return (
    typeof value === "string" &&
    VALID_QUALIFICATION_STATUSES.includes(
      value as ProspectQualificationStatus
    )
  );
}

/**
 * Returns true only for an actual HTTP(S) URL.
 *
 * Evidence sources are persisted intelligence and therefore must not be
 * allowed to contain arbitrary text masquerading as a source.
 */
function isValidHttpUrl(value: string): boolean {
  try {
    const url = new URL(value.trim());

    return (
      url.protocol === "http:" ||
      url.protocol === "https:"
    );
  } catch {
    return false;
  }
}

function parseJsonObject<T>(
  value: unknown,
  fallback: T
): T {
  if (typeof value !== "string" || !value.trim()) {
    return fallback;
  }

  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

function normalizeEvidence(value: unknown): ProspectEvidence[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .slice(0, MAX_EVIDENCE_ITEMS)
    .map((item): ProspectEvidence | null => {
      if (!item || typeof item !== "object") {
        return null;
      }

      const record = item as Record<string, unknown>;

      const observation = optionalString(
        record.observation,
        MAX_TEXT_LENGTH
      );

      const source = optionalString(
        record.source,
        MAX_TEXT_LENGTH
      );

      /*
       * Evidence is persisted intelligence.
       *
       * A source must therefore be a genuine HTTP(S) URL rather than
       * arbitrary text supplied by a caller or malformed persisted data.
       */
      if (
        !observation ||
        !source ||
        !isValidHttpUrl(source)
      ) {
        return null;
      }

      const observedAt = optionalString(
        record.observed_at,
        100
      );

      return {
        observation,
        source,
        ...(observedAt
          ? { observed_at: observedAt }
          : {}),
      };
    })
    .filter(
      (item): item is ProspectEvidence =>
        item !== null
    );
}

function normalizeUnknowns(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .slice(0, MAX_UNKNOWN_ITEMS)
    .filter(
      (item): item is string =>
        typeof item === "string" &&
        item.trim().length > 0
    )
    .map((item) =>
      item.trim().slice(0, MAX_TEXT_LENGTH)
    );
}

/**
 * Converts a database row into the public Prospect model.
 *
 * Database contents are treated as untrusted persisted data. Malformed JSON
 * must not crash the application merely because a single prospect contains
 * damaged evidence or unknowns.
 */
function mapProspectRow(
  row: Record<string, unknown>
): Prospect {
  const prospectType = isProspectType(row.prospect_type)
    ? row.prospect_type
    : "other";

  const qualificationStatus =
    isQualificationStatus(row.qualification_status)
      ? row.qualification_status
      : "needs_review";

  const evidence = normalizeEvidence(
    parseJsonObject<unknown[]>(
      row.evidence,
      []
    )
  );

  const unknowns = normalizeUnknowns(
    parseJsonObject<unknown[]>(
      row.unknowns,
      []
    )
  );

  const confidence =
    row.confidence === null ||
    row.confidence === undefined
      ? undefined
      : Number(row.confidence);

  return {
    id: String(row.id),

    user_id: String(row.user_id),

    source_task_id:
      row.source_task_id === null ||
      row.source_task_id === undefined
        ? undefined
        : optionalString(row.source_task_id),

    name:
      optionalString(row.name, MAX_NAME_LENGTH) ??
      "Unnamed prospect",

    organization:
      optionalString(
        row.organization,
        MAX_NAME_LENGTH
      ),

    role:
      optionalString(
        row.role,
        MAX_NAME_LENGTH
      ),

    email:
      normalizeEmail(row.email),

    prospect_type: prospectType,

    qualification_status:
      qualificationStatus,

    website:
      optionalString(
        row.website,
        MAX_TEXT_LENGTH
      ),

    public_profile_url:
      optionalString(
        row.public_profile_url,
        MAX_TEXT_LENGTH
      ),

    product_id:
      optionalString(row.product_id, 200),

    fit_reason:
      optionalString(row.fit_reason),

    opportunity_signal:
      optionalString(row.opportunity_signal),

    evidence,

    confidence:
      Number.isFinite(confidence)
        ? Math.min(
            Math.max(confidence as number, 0),
            1
          )
        : undefined,

    unknowns,

    created_at:
      String(row.created_at),

    updated_at:
      String(row.updated_at),
  };
}

/* -------------------------------------------------------------------------- */
/* Create                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Creates and persists a prospect intelligence record.
 *
 * Persistence quality rules:
 *
 * - a prospect must have at least one valid evidence item;
 * - a prospect must explain why it fits the target product;
 * - a prospect must contain an observable opportunity / need signal;
 * - a product-linked prospect must identify the product;
 * - evidence is normalized before persistence;
 * - every evidence source must be a valid HTTP(S) URL;
 * - an email, when supplied, must have valid basic email syntax.
 *
 * Email is intentionally not yet a mandatory persistence requirement.
 * The prospecting executor will be upgraded separately to make email-first
 * prospect discovery the operational rule for task-generated prospects.
 */
export async function createProspect(
  input: CreateProspectInput
): Promise<Prospect> {
  const userId = requiredString(
    input.user_id,
    "Prospect user_id",
    500
  );

  const name = requiredString(
    input.name,
    "Prospect name",
    MAX_NAME_LENGTH
  );

  if (!isProspectType(input.prospect_type)) {
    throw new Error(
      `Invalid prospect_type "${input.prospect_type}".`
    );
  }

  const qualificationStatus =
    input.qualification_status ??
    "candidate";

  if (!isQualificationStatus(qualificationStatus)) {
    throw new Error(
      `Invalid qualification_status "${qualificationStatus}".`
    );
  }

  if (
    input.confidence !== undefined &&
    (
      !Number.isFinite(input.confidence) ||
      input.confidence < 0 ||
      input.confidence > 1
    )
  ) {
    throw new Error(
      "Prospect confidence must be between 0 and 1."
    );
  }

  const evidence = normalizeEvidence(
    input.evidence ?? []
  );

  if (evidence.length === 0) {
    throw new Error(
      "A prospect must contain at least one valid HTTP(S) evidence item."
    );
  }

  const fitReason = optionalString(
    input.fit_reason
  );

  if (!fitReason) {
    throw new Error(
      "A prospect must contain a meaningful fit_reason."
    );
  }

  const opportunitySignal = optionalString(
    input.opportunity_signal
  );

  if (!opportunitySignal) {
    throw new Error(
      "A prospect must contain a meaningful opportunity_signal."
    );
  }

  const productId =
    optionalString(input.product_id, 200);

  /*
   * Prospecting intelligence should always be associated with the product
   * that the research was performed for.
   *
   * This does not prevent future non-product prospect records, but it does
   * prevent a product-specific prospecting task from silently persisting
   * productless records.
   */
  if (input.source_task_id && !productId) {
    throw new Error(
      "A task-generated prospect must identify its target product."
    );
  }

const email =
  normalizeEmail(input.email);

/*
 * Email is now the contactability gate for task-generated prospects.
 *
 * Existing prospect records remain compatible with nullable email, but a
 * new prospect created from a task must have a syntactically valid email.
 *
 * This does NOT claim that the mailbox exists. The prospecting executor must
 * establish that the address was legitimately discovered from a public
 * source and preserve that provenance in the evidence.
 */
if (input.source_task_id && !email) {
  throw new Error(
    "A task-generated prospect must contain a valid email address."
  );
}

/*
 * For non-task-created prospects, an email is optional. If one is supplied,
 * however, it must still have valid basic syntax.
 */
if (
  !input.source_task_id &&
  input.email !== undefined &&
  input.email !== null &&
  input.email !== "" &&
  !email
) {
  throw new Error(
    "Prospect email must be a valid email address."
  );
}

  const unknowns = normalizeUnknowns(
    input.unknowns ?? []
  );

  const db = await getDb();

  const id = randomUUID();

  await db.execute({
    sql: `
      INSERT INTO prospects (
        id,
        user_id,
        source_task_id,
        name,
        organization,
        role,
        email,
        prospect_type,
        qualification_status,
        website,
        public_profile_url,
        product_id,
        fit_reason,
        opportunity_signal,
        evidence,
        confidence,
        unknowns
      )
      VALUES (
        @id,
        @user_id,
        @source_task_id,
        @name,
        @organization,
        @role,
        @email,
        @prospect_type,
        @qualification_status,
        @website,
        @public_profile_url,
        @product_id,
        @fit_reason,
        @opportunity_signal,
        @evidence,
        @confidence,
        @unknowns
      )
    `,
    args: {
      id,

      user_id: userId,

      source_task_id:
        optionalString(
          input.source_task_id,
          200
        ) ?? null,

      name,

      organization:
        optionalString(
          input.organization,
          MAX_NAME_LENGTH
        ) ?? null,

      role:
        optionalString(
          input.role,
          MAX_NAME_LENGTH
        ) ?? null,

      email:
        email ?? null,

      prospect_type:
        input.prospect_type,

      qualification_status:
        qualificationStatus,

      website:
        optionalString(
          input.website,
          MAX_TEXT_LENGTH
        ) ?? null,

      public_profile_url:
        optionalString(
          input.public_profile_url,
          MAX_TEXT_LENGTH
        ) ?? null,

      product_id:
        productId ?? null,

      fit_reason:
        fitReason,

      opportunity_signal:
        opportunitySignal,

      evidence:
        JSON.stringify(evidence),

      confidence:
        input.confidence ?? null,

      unknowns:
        JSON.stringify(unknowns),
    },
  });

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE id = ?
        AND user_id = ?
    `,
    args: [id, userId],
  });

  const row = result.rows[0] as unknown as
    | Record<string, unknown>
    | undefined;

  if (!row) {
    throw new Error(
      "Failed to retrieve newly created prospect."
    );
  }

  return mapProspectRow(row);
}

/* -------------------------------------------------------------------------- */
/* Retrieval                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Retrieves a prospect by ID belonging to the specified user.
 *
 * Ownership is part of the query itself so a prospect belonging to another
 * user can never be returned accidentally.
 */
export async function getProspectById(
  userId: string,
  id: string
): Promise<Prospect | null> {
  const normalizedUserId = userId.trim();
  const normalizedId = id.trim();

  if (
    !normalizedUserId ||
    !normalizedId
  ) {
    return null;
  }

  const db = await getDb();

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE id = ?
        AND user_id = ?
      LIMIT 1
    `,
    args: [normalizedId, normalizedUserId],
  });

  const row = result.rows[0] as unknown as
    | Record<string, unknown>
    | undefined;

  return row
    ? mapProspectRow(row)
    : null;
}

/**
 * Lists prospects belonging to a specific user, newest first.
 *
 * All filters are parameterized. The LIMIT value is normalized to prevent
 * invalid or unexpectedly large queries.
 */
export async function listProspects(
  userId: string,
  options?: {
    limit?: number;
    qualification_status?: ProspectQualificationStatus;
    prospect_type?: ProspectType;
    product_id?: string;
  }
): Promise<Prospect[]> {
  const normalizedUserId =
    userId.trim();

  if (!normalizedUserId) {
    return [];
  }

  const db = await getDb();

  const requestedLimit =
    typeof options?.limit === "number" &&
    Number.isFinite(options.limit)
      ? Math.floor(options.limit)
      : 50;

  const limit = Math.min(
    Math.max(requestedLimit, 1),
    200
  );

  const conditions: string[] = [
    "user_id = @user_id",
  ];

  const parameters: Record<
    string,
    unknown
  > = {
    user_id: normalizedUserId,
    limit,
  };

  if (options?.qualification_status) {
    if (
      !isQualificationStatus(
        options.qualification_status
      )
    ) {
      return [];
    }

    conditions.push(
      "qualification_status = @qualification_status"
    );

    parameters.qualification_status =
      options.qualification_status;
  }

  if (options?.prospect_type) {
    if (
      !isProspectType(
        options.prospect_type
      )
    ) {
      return [];
    }

    conditions.push(
      "prospect_type = @prospect_type"
    );

    parameters.prospect_type =
      options.prospect_type;
  }

  if (options?.product_id) {
    const productId =
      options.product_id.trim();

    if (!productId) {
      return [];
    }

    conditions.push(
      "product_id = @product_id"
    );

    parameters.product_id =
      productId;
  }

  const result = await db.execute({
    sql: `
      SELECT *
      FROM prospects
      WHERE ${conditions.join(" AND ")}
      ORDER BY created_at DESC
      LIMIT @limit
    `,
    args: parameters as InArgs,
  });

  const rows = result.rows as unknown as Array<
    Record<string, unknown>
  >;

  return rows.map(mapProspectRow);
}